### ISSUE TITLE
Referencing existing H-Revolve implementation in paper

### ISSUE THREAD

**Issue by matt-graham** [firedrakeproject/checkpoint_schedules#54]
Raising as part of https://github.com/openjournals/joss-reviews/issues/6148

The JOSS paper draft refers to a 'proof-of-concept' implementation of H-Revolve

https://github.com/firedrakeproject/checkpoint_schedules/blob/055c881297fea83f5531cfb2b6e2a33f3bc1d18f/docs/paper/paper.md?plain=1#L98-L103

From a bit of searching I came across

https://gitlab.inria.fr/adjoint-computation/H-Revolve

which I assume is what is being referred to? This should ideally be directly referenced in the JOSS paper (with citation including a URL pointing to the repository) and some explanation given to how it differs from the package here, as it appears to implement several of the same checkpoint schedule algorithms. 

I also note that the three contributors on that repository are all authors on the JOSS paper, though with the exception of David Ham, do not appear to have made direct contributions to the repository here. Is the basis for including these additional authors that `checkpointing_schedules` is partly inspired or derived from this previous package? If so, again this should be clarified in the paper ideally.

**Comment by Ig-dolci** [comment]
@matt-graham
 
`checkpoint_schedules` does indeed incorporate code from the reference implementation presented in Hermann & Pallez (2020), though several changes and fixes were required in order to make the code production-ready. Hermann and Pallez contributed to those fixes, though they did not personally make commits to the new repository. We have made the contributions of all the authors more explicit by introducing an author contribution section in the paper, and by adding copyright headers with accurate authorship information to all of the source files. We have not added a direct link to the previous git repository, because the canonical location for that code is now here and because the long-term status of the other repository is uncertain. That repository referenced from Hermann & Pallez (2020) as is appropriate because that version of the software was used in that paper.
 
There are also pull requests that go along with that:
- [PR 58](https://github.com/firedrakeproject/checkpoint_schedules/pull/58) adds copyright headers with accurate authorship information to all of the source files.
-  [PR 61](https://github.com/firedrakeproject/checkpoint_schedules/pull/61) creates the author contribution section in the paper.

**Comment by matt-graham** [comment]
@Ig-dolci - thanks for clarifying and adding the author contribution section to paper.
