### ISSUE TITLE
Incorrect Use of Move Instead of Copy in MixedCheckpointSchedule

### ISSUE THREAD

**Issue by Ig-dolci** [firedrakeproject/checkpoint_schedules#72]
**Description**
The generated action sequence for the `MixedCheckpointSchedule` appears to have duplicate 'Move' actions. Based on the workflow and storage transitions, these actions are more closely aligned with the `Copy` action.

- Steps to reproduce:
```
from checkpoint_schedules import MixedCheckpointSchedule, StorageType

total_steps = 10
schedule = MixedCheckpointSchedule(total_steps, 2, storage=StorageType.RAM)
for _, cp_action in enumerate(schedule):
    print(_, cp_action)
```

- Action Sequence:
See  9 and 13 actions. Similar patterns occur later in the sequence (e.g., indices 20, 24, 26, 33).
```
0 Forward(0, 6, True, False, StorageType.RAM)
1 Forward(6, 9, True, False, StorageType.RAM)
2 Forward(9, 10, False, True, StorageType.WORK)
3 EndForward()
4 Reverse(10, 9, True)
5 Copy(6, StorageType.RAM, StorageType.WORK)
6 Forward(6, 8, False, False, StorageType.WORK)
7 Forward(8, 9, False, True, StorageType.WORK)
8 Reverse(9, 8, True)
9 Move(6, StorageType.RAM, StorageType.WORK)
10 Forward(6, 7, False, True, StorageType.RAM)
11 Forward(7, 8, False, True, StorageType.WORK)
12 Reverse(8, 7, True)
13 Move(6, StorageType.RAM, StorageType.WORK)
14 Reverse(7, 6, True)
15 Copy(0, StorageType.RAM, StorageType.WORK)
16 Forward(0, 3, False, False, StorageType.WORK)
17 Forward(3, 5, True, False, StorageType.RAM)
18 Forward(5, 6, False, True, StorageType.WORK)
19 Reverse(6, 5, True)
20 Move(3, StorageType.RAM, StorageType.WORK)
21 Forward(3, 4, False, True, StorageType.RAM)
22 Forward(4, 5, False, True, StorageType.WORK)
23 Reverse(5, 4, True)
24 Move(3, StorageType.RAM, StorageType.WORK)
25 Reverse(4, 3, True)
26 Move(0, StorageType.RAM, StorageType.WORK)
27 Forward(0, 1, False, True, StorageType.RAM)
28 Forward(1, 2, False, True, StorageType.RAM)
29 Forward(2, 3, False, True, StorageType.WORK)
30 Reverse(3, 2, True)
31 Move(1, StorageType.RAM, StorageType.WORK)
32 Reverse(2, 1, True)
33 Move(0, StorageType.RAM, StorageType.WORK)
34 Reverse(1, 0, True)
35 EndReverse()
```

**Comment by jrmaddison** [comment]
This schedule is tested as part of the tlm_adjoint test suite. Bugs are obviously possible (particularly in the checkpoint_schedules to tlm_adjoint schedules translation layer in https://github.com/tlm-adjoint/tlm_adjoint/blob/main/tlm_adjoint/checkpoint_schedules/checkpoint_schedules.py), but for the above

```
9 Move(6, StorageType.RAM, StorageType.WORK)
10 Forward(6, 7, False, True, StorageType.RAM)
11 Forward(7, 8, False, True, StorageType.WORK)
12 Reverse(8, 7, True)
13 Move(6, StorageType.RAM, StorageType.WORK)
14 Reverse(7, 6, True)
```

Action 9 loads a forward restart checkpoint, and deletes it freeing a checkpointing unit. Action 10 stores adjoint dependency data in a checkpointing unit (a 'non-linear dependency data checkpoint'), then action 11 stores adjoint dependency data in working memory (the 'intermediate storage' in the tlm_adjoint model). That lets the adjoint reverse over two steps without a forward advance. The load in action 13 deletes the adjoint dependency data from the checkpointing unit, because it's only used once, for an adjoint advance.

**Comment by Ig-dolci** [comment]
Ahh. I see... It is not moving the same set. Thanks.
